# Site settings
title: spalger's speakeasy
email: email@spalger.com
description: >
  Just sharing what I've learned, and recording things I don't want to forget.
baseurl: ""
url: "http://spalger.github.io"
twitter_username: spalger
github_username:  spenceralger
timezone:      "America/Phoenix"

# Custom vars
tags_route:  "/tags/@tag@"

# Where things are
source:      ./src
gems:
  - emoji_for_jekyll
  - octopress-autoprefixer
collections:
  - projects
  # - libraries
  # - experience
  # - expertise

# conversion
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge