# Site settings
title: spalger's speakeasy
email: email@spalger.com
description: >
  Just sharing what I've learned, and recording things I don't want to forget.
baseurl: ""
url: "http://spalger.github.io"
twitter_username: spenceralger
github_username:  spalger
timezone:      "America/Phoenix"

# Custom vars
tags_route:  "/tags/@tag@"
production: false

# Where things are
source:      ./src
sass_dir: _assets/style
include:
  - .env
  - .static
gems:
  - emoji_for_jekyll
  - jekyll-auto-image
  - jekyll-sitemap

collections:
  - projects
  # - libraries
  # - experience
  # - expertise

safe: false

# conversion
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

#
# Plugin: jekyll-assets
#
assets:

  #
  # Pathnames where to find assets relative to the root of the site.
  #
  sources:
    - _assets/js
    - _assets/style
    - _assets/imgs
    - _assets/components

  cachebust: none
  debug: true