
# SEO settings
title: "Spencer Alger"
title2: "" # default: ""
description: "Personal blog"
keywords: "spalger, spencer alger, blog, javascript, node.js"
url: https://spalger.com # site url
baseurl: null

google_analytics: UA-86810340-1
repo: http://github.com/spalger/spalger.com
disqus_shortname: "spalgercom"
twitter_username: "spalger"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Spencer Alger"
  job      : null
  bio      : "Software Engineer, recovering karaoke junkie"
  thumb    : /images/author.jpg
  email    : email@spalger.com
  url      : https://spalger.com
  github   : https://github.com/spalger
  twitter  : https://twitter.com/spalger
  facebook : null
  linkedin : null

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@spalger"

gems:
  - bourbon
  - jekyll-paginate
  - emoji_for_jekyll
  - jekyll-auto-image
  - jekyll-sitemap

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  - projects

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
