# Site settings
title: spalger speaks
email: email@spalger.com
description: >
  Just some things I want to remember, or I think others might find interesting.
baseurl: "/speakeasy"
url: "http://spalger.github.io"
twitter_username: spalger
github_username:  spenceralger

# Build settings
markdown: kramdown
